[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"


[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "no-cache"
    Pragma = "no-cache"